module Maps(map01, map01data) where

import Data.Geography
import Data.Geography.Styles

-- | Dummy map
map01 = loadMap loadSimpleStyle map01data

map01data = ["TGGGGGGGGGRGGGGGGGGGGGGWWWWWWGGGDDDDDDDD",
             "GGGGGGGGGGRGGGGGTGGGGGWWWWWWWGGGGGDDDDDD",
             "GGGTGGGGGGRGGGGGGGGGGGWWWWWWWGGGGGTGDDDD",
             "GGOOOOOOOGRGGGGTTGGGGGWWWWWWWGGGGGGGDDDD",
             "GGOGGGGGOGRGGGGGGGGGGGGGWWWWWGGGGGTGDDDD",
             "GGOOOOOOOGRGGGGGTGGGGGGGGGWWGGGGGGGGGGGG",
             "GGGGTTGGGGRRRRRRRRRRRRRGGGWWGGGGGGGGGGGG",
             "GGTGGGGGGGGGGGGGGGGGGGRGGGWWGGGGGGGGGGGG",
             "GGGGGGGTGGGGGGGGTGGGGGRGGGWWGGGGGGGGGGGG",
             "TTGTGGGGGGGGGGGTTGGGGGRGGGWWWWGGGGGGGGGG",
             "TTGGGGGGGTGGGDDDGDDDDGRGGGGGWWWGGGGGGGGG",
             "TTTTGGGGGGGGGDDDDDDDDGGRGGGGGGGWWGGGGGGG"]
